services:
  backend:
    build:
      context: ./Document_SPIT_BE
      target: final
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DOTNET_ENV_PATH=/app/.env
    working_dir: /app
    restart: always
    networks:
      - internal

  frontend:
    build:
      context: ./frontend_document
      target: runner
    ports:
      - "1111:1111"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - internal  

networks:
  internal:
    driver: bridge
